language: node_js
node_js:
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
before_install:
  - npm install
script:
  - npm test
  - node -v

notifications:
  email:
    - $GITHUB_EMAIL

jobs:
  include:
    - stage: npm release
      node_js: '10'
      script: echo "Deploying $TRAVIS_TAG"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        on:
          tags: true
